//随机产生的数据
let simulateData = [
    {
        id: random(),
        userid: random(),
        nickname: `用户${random(100, 99999)}`,
        avatar: 'images/1.png',
        comment: `这是随机产生的序列号为${random(19987, 123213)}评论`,
        description: `序列号${random(10, 30)}`,
        date: `${random(1, 10)}`,
    },
    {
        id: random(),
        userid: random(),
        nickname: `用户${random(100, 99999)}`,
        avatar: 'images/2.png',
        comment: `这是随机产生的序列号为${random(19987, 123213)}评论`,
        description: `序列号${random(10, 30)}`,
        date: `${random(1, 10)}`,
    },
    {
        id: random(),
        userid: random(),
        nickname: `用户${random(100, 99999)}`,
        avatar: 'images/3.png',
        comment: `这是随机产生的序列号为${random(19987, 123213)}评论`,
        description: `序列号${random(10, 30)}`,
        date: `${random(1, 10)}`,
    },
    {
        id: random(),
        userid: random(),
        nickname: `用户${random(100, 999)}`,
        avatar: 'images/4.png',
        comment: `这是随机产生的序列号为${random(19987, 123213)}评论`,
        description: `序列号${random(10, 30)}`,
        date: `${random(1, 10)}`,
    },
    {
        id: random(),
        userid: random(),
        nickname: `用户${random(100, 99999)}`,
        avatar: 'images/5.png',
        comment: `这是随机产生的序列号为${random(19987, 123213)}评论`,
        description: `序列号${random(10, 30)}`,
        date: `${random(1, 10)}`,
    },
    {
        id: random(),
        userid: random(),
        nickname: `用户${random(100, 99999)}`,
        avatar: 'images/6.png',
        comment: `这是随机产生的序列号为${random(19987, 123213)}评论`,
        description: `序列号${random(10, 30)}`,
        date: `${random(1, 10)}`,
    },

]
